"""
models.py — SentinelFlow SQLAlchemy ORM models
===============================================
Three time-series tables that back the core data-ingestion pipeline:

  PortManifests    — container volumes and dwell times per port per timestamp
  FactoryOutputs   — scheduled vs. actual production capacity per factory
  SentimentData    — NLP risk scores derived from news and social media streams

All tables share a common design contract:
  • Primary key  : UUID generated server-side (no client-supplied IDs)
  • Timestamps   : timezone-aware UTC, set automatically on insert
  • Soft deletes : `deleted_at` nullable column — hard deletes are avoided so
                   the time-series history is never destroyed
  • Indexes      : added on every column used in WHERE / ORDER BY clauses in
                   the expected query patterns (timestamp ranges, foreign-key
                   look-ups, enum filters)

Import and usage
----------------
    from database import Base          # shared declarative base
    from models import PortManifest, FactoryOutput, SentimentData

    # In an Alembic env.py, import Base so autogenerate detects the tables:
    from models import Base            # re-exported for convenience

Alembic migrations
------------------
    alembic revision --autogenerate -m "initial tables"
    alembic upgrade head
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum as SAEnum,
    Float,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from database import Base


# ── Helpers ───────────────────────────────────────────────────────────────────

def _uuid_pk() -> Mapped[uuid.UUID]:
    """Reusable server-side UUID primary key column."""
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Surrogate primary key — UUID v4 generated by PostgreSQL.",
    )


def _utcnow() -> Mapped[datetime]:
    """
    Reusable event timestamp column.
    Defaults to the database server's current UTC time so that records
    inserted from any application node share a consistent clock.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        index=True,
        comment="UTC timestamp of the real-world event being recorded.",
    )


def _created_at() -> Mapped[datetime]:
    """Row-insertion audit timestamp — immutable after insert."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        comment="UTC timestamp when this row was first inserted.",
    )


# ── Enums ─────────────────────────────────────────────────────────────────────

class SentimentSourceType(str, enum.Enum):
    """
    Tracks which ingestion stream produced a SentimentData row.
    Stored as a native PostgreSQL ENUM for referential safety and
    query-plan efficiency.
    """
    NEWS   = "news"    # wire-service / media articles (DistilBERT NLP pipeline)
    SOCIAL = "social"  # social-media posts (Twitter/X, LinkedIn sentiment scraper)


# ── PortManifests ─────────────────────────────────────────────────────────────

class PortManifest(Base):
    """
    One row per port reporting interval.

    Captures the volume of containers present at a port and how long they
    are sitting before departure (dwell time). Sustained high dwell times
    relative to the port's historical baseline are the primary early-warning
    signal for congestion bottlenecks in the GNN model.

    Columns
    -------
    id               — UUID surrogate key
    port_name        — IATA / UN/LOCODE identifier, e.g. "CN SHA" or "CNSHA"
    port_code        — Optional standardised 5-char UN/LOCODE for graph joins
    container_volume — TEU count at time of snapshot (Twenty-foot Equivalent Units)
    dwell_time       — Average hours a container has waited at the port
    capacity_pct     — (container_volume / port design capacity) × 100;
                       computed by the ingestion pipeline, stored for fast querying
    timestamp        — UTC time the manifest snapshot was taken at the port
    created_at       — UTC row-insertion time (audit; never equals timestamp for
                       ingestion pipelines with any latency)
    deleted_at       — NULL = active; non-NULL = soft-deleted
    """

    __tablename__ = "port_manifests"
    __table_args__ = (
        # Composite uniqueness: one snapshot per port per minute prevents
        # duplicate ingestion from idempotent stream replays.
        UniqueConstraint("port_code", "timestamp", name="uq_port_manifest_port_ts"),
        CheckConstraint("container_volume >= 0",  name="ck_port_manifest_vol_gte0"),
        CheckConstraint("dwell_time >= 0",        name="ck_port_manifest_dwell_gte0"),
        CheckConstraint(
            "capacity_pct IS NULL OR (capacity_pct >= 0 AND capacity_pct <= 200)",
            name="ck_port_manifest_capacity_range",
        ),
        # Partial index: fast look-up of active (non-deleted) records by port
        Index(
            "ix_port_manifests_port_code_active",
            "port_code",
            "timestamp",
            postgresql_where="deleted_at IS NULL",
        ),
        {"comment": "Time-series container volume and dwell snapshots per port."},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()

    port_name: Mapped[str] = mapped_column(
        String(120),
        nullable=False,
        comment="Human-readable port name, e.g. 'Port of Shanghai'.",
    )
    port_code: Mapped[str | None] = mapped_column(
        String(10),
        nullable=True,
        index=True,
        comment="UN/LOCODE or IATA code, e.g. 'CNSHA'. Used for graph node joins.",
    )
    container_volume: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Snapshot TEU count (Twenty-foot Equivalent Units) at the port.",
    )
    dwell_time: Mapped[float] = mapped_column(
        Numeric(precision=8, scale=2),
        nullable=False,
        comment="Average container dwell time in hours at time of snapshot.",
    )
    capacity_pct: Mapped[float | None] = mapped_column(
        Numeric(precision=6, scale=2),
        nullable=True,
        comment="(container_volume / port capacity) × 100. NULL if capacity unknown.",
    )
    timestamp: Mapped[datetime] = _utcnow()
    created_at: Mapped[datetime] = _created_at()
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Non-NULL signals a soft delete; row excluded from active queries.",
    )

    def __repr__(self) -> str:
        return (
            f"<PortManifest port={self.port_code or self.port_name!r} "
            f"vol={self.container_volume} TEU dwell={self.dwell_time}h "
            f"ts={self.timestamp.isoformat()}>"
        )


# ── FactoryOutputs ────────────────────────────────────────────────────────────

class FactoryOutput(Base):
    """
    One row per factory per production shift/interval.

    The ratio of actual_output to capacity_scheduled drives the inventory
    availability signal fed into the XGBoost demand-forecasting model.
    A sustained shortfall (utilisation_pct << 100) upstream of a congested
    port compounds the bottleneck risk score in the graph.

    Columns
    -------
    id                  — UUID surrogate key
    factory_id          — Opaque identifier matching the IoT MQTT client ID
    factory_name        — Human label (optional, set during device registration)
    region              — Geographic region tag for aggregated analytics
    capacity_scheduled  — Planned production units for this interval
    actual_output       — Units actually produced (may exceed scheduled if OT run)
    utilisation_pct     — (actual_output / capacity_scheduled) × 100;
                          pre-computed to avoid repeated division in queries
    shift_duration_hrs  — Length of the production interval in hours
    timestamp           — Start of the production interval (UTC)
    created_at          — Row-insertion audit timestamp
    deleted_at          — Soft-delete sentinel
    """

    __tablename__ = "factory_outputs"
    __table_args__ = (
        UniqueConstraint(
            "factory_id", "timestamp",
            name="uq_factory_output_factory_ts",
        ),
        CheckConstraint("capacity_scheduled > 0",  name="ck_factory_capacity_gt0"),
        CheckConstraint("actual_output >= 0",      name="ck_factory_output_gte0"),
        CheckConstraint(
            "shift_duration_hrs IS NULL OR shift_duration_hrs > 0",
            name="ck_factory_shift_duration_gt0",
        ),
        Index(
            "ix_factory_outputs_factory_ts_active",
            "factory_id",
            "timestamp",
            postgresql_where="deleted_at IS NULL",
        ),
        Index("ix_factory_outputs_region", "region"),
        {"comment": "Time-series production output readings per factory shift."},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()

    factory_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Stable factory identifier — matches MQTT client_id in IoT telemetry.",
    )
    factory_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        comment="Optional human-readable factory label set at device registration.",
    )
    region: Mapped[str | None] = mapped_column(
        String(80),
        nullable=True,
        comment="Geographic region tag, e.g. 'APAC', 'EMEA'. Used in aggregations.",
    )
    capacity_scheduled: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
        comment="Planned production units for this interval.",
    )
    actual_output: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
        comment="Units produced. May exceed capacity_scheduled on overtime runs.",
    )
    utilisation_pct: Mapped[float | None] = mapped_column(
        Numeric(precision=6, scale=2),
        nullable=True,
        comment="(actual_output / capacity_scheduled) × 100. Pre-computed at insert.",
    )
    shift_duration_hrs: Mapped[float | None] = mapped_column(
        Numeric(precision=5, scale=2),
        nullable=True,
        comment="Duration of the production interval in hours.",
    )
    timestamp: Mapped[datetime] = _utcnow()
    created_at: Mapped[datetime] = _created_at()
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Non-NULL signals a soft delete.",
    )

    def __repr__(self) -> str:
        util = (
            f"{float(self.utilisation_pct):.1f}%"
            if self.utilisation_pct is not None
            else "N/A"
        )
        return (
            f"<FactoryOutput factory={self.factory_id!r} "
            f"scheduled={self.capacity_scheduled} actual={self.actual_output} "
            f"util={util} ts={self.timestamp.isoformat()}>"
        )


# ── SentimentData ─────────────────────────────────────────────────────────────

class SentimentDatum(Base):
    """
    One row per classified text document from the NLP ingestion pipelines.

    Risk scores from both the news wire (DistilBERT) and social-media
    (lightweight VADER + custom fine-tune) streams are normalised to
    [0.0, 1.0] before storage. The Isolation Forest anomaly detector
    treats a spike in aggregate risk_score as an early signal of a
    labour dispute, regulatory event, or geopolitical disruption that
    has not yet manifested in port congestion data.

    Columns
    -------
    id           — UUID surrogate key
    source_type  — 'news' | 'social'  (PostgreSQL ENUM)
    source_url   — Origin URL or MQTT topic string; nullable for scrubbed data
    language     — ISO 639-1 language code of raw_text, e.g. 'en', 'zh'
    risk_score   — Normalised [0.0, 1.0] risk score from the NLP classifier
    confidence   — Model confidence in the risk_score classification [0.0, 1.0]
    raw_text     — Original article excerpt / social post (max 8 KB).
                   Scrubbed of PII before storage per data-governance policy.
    entities     — JSON array of extracted named entities (ports, carriers, etc.)
                   stored as plain TEXT for simplicity; cast to JSONB in a future
                   migration when filtering on entities is required.
    timestamp    — UTC publication time of the source document
    created_at   — Row-insertion audit timestamp
    deleted_at   — Soft-delete sentinel
    """

    __tablename__ = "sentiment_data"
    __table_args__ = (
        CheckConstraint(
            "risk_score >= 0.0 AND risk_score <= 1.0",
            name="ck_sentiment_risk_score_range",
        ),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)",
            name="ck_sentiment_confidence_range",
        ),
        # Composite index for the most common analytics query:
        # "high-risk news items in the last N hours"
        Index(
            "ix_sentiment_source_type_risk_ts",
            "source_type",
            "risk_score",
            "timestamp",
            postgresql_where="deleted_at IS NULL",
        ),
        Index("ix_sentiment_language", "language"),
        {"comment": "NLP-classified risk scores from news and social media streams."},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()

    source_type: Mapped[SentimentSourceType] = mapped_column(
        SAEnum(
            SentimentSourceType,
            name="sentiment_source_type",   # PostgreSQL ENUM type name
            create_type=True,               # Alembic will CREATE TYPE automatically
        ),
        nullable=False,
        index=True,
        comment="Origin stream: 'news' (DistilBERT) or 'social' (VADER fine-tune).",
    )
    source_url: Mapped[str | None] = mapped_column(
        String(2048),
        nullable=True,
        comment="Source URL or MQTT topic. NULL for aggregated / scrubbed records.",
    )
    language: Mapped[str | None] = mapped_column(
        String(8),
        nullable=True,
        comment="ISO 639-1 language code of raw_text, e.g. 'en', 'zh', 'ja'.",
    )
    risk_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Normalised risk score in [0.0, 1.0]. 1.0 = maximum supply-chain risk.",
    )
    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Model classification confidence in [0.0, 1.0]. NULL if not reported.",
    )
    raw_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="PII-scrubbed article excerpt or social post. Hard limit ~8 KB enforced in schema.",
    )
    entities: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="JSON array of named entities extracted by the NLP pipeline, e.g. '[\"Port of Shanghai\"]'.",
    )
    timestamp: Mapped[datetime] = _utcnow()
    created_at: Mapped[datetime] = _created_at()
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Non-NULL signals a soft delete.",
    )

    def __repr__(self) -> str:
        return (
            f"<SentimentDatum source={self.source_type.value!r} "
            f"risk={self.risk_score:.3f} lang={self.language!r} "
            f"ts={self.timestamp.isoformat()}>"
        )


# Re-export Base so Alembic env.py can do: from models import Base
__all__ = [
    "Base",
    "SentimentSourceType",
    "PortManifest",
    "FactoryOutput",
    "SentimentDatum",
]
