"""Initial schema

Revision ID: 9b43edade4a9
Revises: 81692e4e0075
Create Date: 2026-04-04 21:52:17.423296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b43edade4a9'
down_revision: Union[str, None] = '81692e4e0075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_outputs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate primary key — UUID v4 generated by PostgreSQL.'),
    sa.Column('factory_id', sa.String(length=64), nullable=False, comment='Stable factory identifier — matches MQTT client_id in IoT telemetry.'),
    sa.Column('factory_name', sa.String(length=200), nullable=True, comment='Optional human-readable factory label set at device registration.'),
    sa.Column('region', sa.String(length=80), nullable=True, comment="Geographic region tag, e.g. 'APAC', 'EMEA'. Used in aggregations."),
    sa.Column('capacity_scheduled', sa.BigInteger(), nullable=False, comment='Planned production units for this interval.'),
    sa.Column('actual_output', sa.BigInteger(), nullable=False, comment='Units produced. May exceed capacity_scheduled on overtime runs.'),
    sa.Column('utilisation_pct', sa.Numeric(precision=6, scale=2), nullable=True, comment='(actual_output / capacity_scheduled) × 100. Pre-computed at insert.'),
    sa.Column('shift_duration_hrs', sa.Numeric(precision=5, scale=2), nullable=True, comment='Duration of the production interval in hours.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the real-world event being recorded.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this row was first inserted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Non-NULL signals a soft delete.'),
    sa.CheckConstraint('actual_output >= 0', name='ck_factory_output_gte0'),
    sa.CheckConstraint('capacity_scheduled > 0', name='ck_factory_capacity_gt0'),
    sa.CheckConstraint('shift_duration_hrs IS NULL OR shift_duration_hrs > 0', name='ck_factory_shift_duration_gt0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'timestamp', name='uq_factory_output_factory_ts'),
    comment='Time-series production output readings per factory shift.'
    )
    op.create_index(op.f('ix_factory_outputs_factory_id'), 'factory_outputs', ['factory_id'], unique=False)
    op.create_index('ix_factory_outputs_factory_ts_active', 'factory_outputs', ['factory_id', 'timestamp'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_factory_outputs_region', 'factory_outputs', ['region'], unique=False)
    op.create_index(op.f('ix_factory_outputs_timestamp'), 'factory_outputs', ['timestamp'], unique=False)
    op.create_table('port_manifests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate primary key — UUID v4 generated by PostgreSQL.'),
    sa.Column('port_name', sa.String(length=120), nullable=False, comment="Human-readable port name, e.g. 'Port of Shanghai'."),
    sa.Column('port_code', sa.String(length=10), nullable=True, comment="UN/LOCODE or IATA code, e.g. 'CNSHA'. Used for graph node joins."),
    sa.Column('container_volume', sa.Integer(), nullable=False, comment='Snapshot TEU count (Twenty-foot Equivalent Units) at the port.'),
    sa.Column('dwell_time', sa.Numeric(precision=8, scale=2), nullable=False, comment='Average container dwell time in hours at time of snapshot.'),
    sa.Column('capacity_pct', sa.Numeric(precision=6, scale=2), nullable=True, comment='(container_volume / port capacity) × 100. NULL if capacity unknown.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the real-world event being recorded.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this row was first inserted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Non-NULL signals a soft delete; row excluded from active queries.'),
    sa.CheckConstraint('capacity_pct IS NULL OR (capacity_pct >= 0 AND capacity_pct <= 200)', name='ck_port_manifest_capacity_range'),
    sa.CheckConstraint('container_volume >= 0', name='ck_port_manifest_vol_gte0'),
    sa.CheckConstraint('dwell_time >= 0', name='ck_port_manifest_dwell_gte0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_code', 'timestamp', name='uq_port_manifest_port_ts'),
    comment='Time-series container volume and dwell snapshots per port.'
    )
    op.create_index(op.f('ix_port_manifests_port_code'), 'port_manifests', ['port_code'], unique=False)
    op.create_index('ix_port_manifests_port_code_active', 'port_manifests', ['port_code', 'timestamp'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_port_manifests_timestamp'), 'port_manifests', ['timestamp'], unique=False)
    op.create_table('sentiment_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate primary key — UUID v4 generated by PostgreSQL.'),
    sa.Column('source_type', sa.Enum('NEWS', 'SOCIAL', name='sentiment_source_type'), nullable=False, comment="Origin stream: 'news' (DistilBERT) or 'social' (VADER fine-tune)."),
    sa.Column('source_url', sa.String(length=2048), nullable=True, comment='Source URL or MQTT topic. NULL for aggregated / scrubbed records.'),
    sa.Column('language', sa.String(length=8), nullable=True, comment="ISO 639-1 language code of raw_text, e.g. 'en', 'zh', 'ja'."),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Normalised risk score in [0.0, 1.0]. 1.0 = maximum supply-chain risk.'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Model classification confidence in [0.0, 1.0]. NULL if not reported.'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='PII-scrubbed article excerpt or social post. Hard limit ~8 KB enforced in schema.'),
    sa.Column('entities', sa.Text(), nullable=True, comment='JSON array of named entities extracted by the NLP pipeline, e.g. \'["Port of Shanghai"]\'.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the real-world event being recorded.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this row was first inserted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Non-NULL signals a soft delete.'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_sentiment_confidence_range'),
    sa.CheckConstraint('risk_score >= 0.0 AND risk_score <= 1.0', name='ck_sentiment_risk_score_range'),
    sa.PrimaryKeyConstraint('id'),
    comment='NLP-classified risk scores from news and social media streams.'
    )
    op.create_index(op.f('ix_sentiment_data_source_type'), 'sentiment_data', ['source_type'], unique=False)
    op.create_index(op.f('ix_sentiment_data_timestamp'), 'sentiment_data', ['timestamp'], unique=False)
    op.create_index('ix_sentiment_language', 'sentiment_data', ['language'], unique=False)
    op.create_index('ix_sentiment_source_type_risk_ts', 'sentiment_data', ['source_type', 'risk_score', 'timestamp'], unique=False, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_source_type_risk_ts', table_name='sentiment_data', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_sentiment_language', table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_timestamp'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_source_type'), table_name='sentiment_data')
    op.drop_table('sentiment_data')
    op.drop_index(op.f('ix_port_manifests_timestamp'), table_name='port_manifests')
    op.drop_index('ix_port_manifests_port_code_active', table_name='port_manifests', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_port_manifests_port_code'), table_name='port_manifests')
    op.drop_table('port_manifests')
    op.drop_index(op.f('ix_factory_outputs_timestamp'), table_name='factory_outputs')
    op.drop_index('ix_factory_outputs_region', table_name='factory_outputs')
    op.drop_index('ix_factory_outputs_factory_ts_active', table_name='factory_outputs', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_factory_outputs_factory_id'), table_name='factory_outputs')
    op.drop_table('factory_outputs')
    # ### end Alembic commands ###